### ISSUE TITLE
License question/request

### ISSUE THREAD

**Issue by rmg** [gvarsanyi/sync-exec#10]
The README cites some advantages of this module over exec-sync, but this module is GPLv2 instead of MIT like exec-sync. I'm curious if that was intentional and what your thoughts are on relicensing under an MIT license instead.

The problem is that some common interpretations of the GPL (particularly the Free Software Foundation's) suggest that the GPL reciprocity extends through dependencies, which means any module that depends on this one, any modules that depend on them, and so on, are all caught up in a rather ugly licensing mess that would all go away if this module was licensed differently.

I believe such a change would technically require agreement by anyone who has contributed, which GitHub says is:
 - [ ] @gvarsanyi
 - [ ] @NessDan 
 - [ ] @typicode
 - [ ] @ddsol

Thoughts?

**Comment by gvarsanyi** [comment]
There's no specific reason, I generally use GPLv2 for my open source code, and I generally prefer the dependents to stay open source too.
I'll assume you need MIT, so I am changing it. Cheers! :)

**Comment by rmg** [comment]
@gvarsanyi thanks!

The problem is paranoid corporate lawyers preventing anything called GPL onto their company's network, which prevented use of this module and any module that included it anywhere in their dependency tree. In other words, it was a potential hurdle for some large/conservative enterprises adopting node ;-)
