### ISSUE TITLE
clarification needed on license

### ISSUE THREAD

**Issue by vinbarnes** [gvarsanyi/sync-exec#15]
Hello @gvarsanyi. Could you help clarify what the license is for this project? There is a [GPL license](https://github.com/gvarsanyi/sync-exec/blob/master/LICENSE) included in the project root but [MIT is listed](https://github.com/gvarsanyi/sync-exec/blob/master/package.json#L23) in package.json manifest. Thanks.

**Comment by gvarsanyi** [comment]
fixed in master, released to npm as version 0.6.2

**Comment by vinbarnes** [comment]
Thanks! :heart:
