### ISSUE TITLE
Trying to use on a windows box with no luck

### ISSUE THREAD

**Issue by corydorning** [gvarsanyi/sync-exec#4]
I was just curious if this package was compatible with Windows. The following command works within OSX but in my windows environment it cause my gulp script to just hang.

```
exec('git log -n 1 --pretty=format:"%H" | head -c9').stdout
```

**Comment by NessDan** [comment]
Same. Everyone on my team is on a Mac except for me. Unfortunately, I'm the only one experiencing problems... :+1:

**Comment by gvarsanyi** [comment]
Sorry guys, did not have the chance to test it on Windows.
NessDan put up a PR to fix it, I am merging it in and releasing soon.

Note that nodejs 0.12 is out and is supposed to give you this natively.
